### ISSUE TITLE
Past infractions show up occasionally

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#402]
![screen shot 2015-04-02 at 18 30 06](https://cloud.githubusercontent.com/assets/7715330/6968350/619d7128-d966-11e4-8a83-4f4e8a965e20.png)
![screen shot 2015-04-02 at 18 30 09](https://cloud.githubusercontent.com/assets/7715330/6968351/61baa8ce-d966-11e4-8df5-e7a328bcd48d.png)
People are also complaining about getting kicked.

**Comment by ParaSpider** [comment]
It happens as the server regenerates its stats. I think this was already addressed.

**Comment by KyloCode** [comment]
Oh if so, then awesome. I thought I fixed this, so, good.

**Comment by pelpelajax** [comment]
@KyloCode It's still happening to other players.

**Comment by Flueh** [comment]
Still happens to me... I get kicked for my past infractions.

**Comment by javipepe** [comment]
I got kicked a little bit earlier today for my almost one year old *appealed* ban. I can of course join back. So it still happens.

By the way, does the server regenerate at a certain hour? So I can avoid playing at that time.

**Comment by Aki35** [comment]
Can confirm this still happens on occasion.

**Comment by pelpelajax** [comment]
@KyloCode - Saw a push, is it fixed?

**Comment by KyloCode** [comment]
I'll close it, pretty sure my fix worked. Open if otherwise.
