### ISSUE TITLE
Items appear in backpack...

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#585]
![image](https://cloud.githubusercontent.com/assets/6472584/8503191/3aac55be-2189-11e5-94d2-d3c45ba931c2.png)
Originally reported by seth, happened to me to. Seth and I did not buy any wings, he had 4, I had 2. I bought the wolf though.

**Comment by KyloCode** [comment]
Weird, looking into it.

**Comment by Sethskype** [comment]
I'll continue on to this.

I actually got 4 wings, and 2 lightning sticks. They were all infinite

**Comment by IcedCode** [comment]
Out of interest had you bought these before IE Have you bought a lightning sticks a while before this happened or wings aswell.

Only saying this because I bought 1 lightning staff close to the Omega release day then when Kylo pushed the shop update I got 1 lightning staff again thats permenant.

**Comment by steven5703** [comment]
@IcedCode Yep
This was fixed

**Comment by Sethskype** [comment]
Steven. This is not fixed. I still have two extra lightning staffs for infinite time
