### ISSUE TITLE
Subscriptions don't work on the forums.

### ISSUE THREAD

**Issue by Acceqted** [Avicus/Issues#934]
Self explanatory.

**Comment by AustinLMayes** [comment]
Fixed

**Comment by flohlen** [comment]
reopen please, it's not fixed. I still get no notification next to the "My Subscriptions" tab.
